This is a library for controlling a pan and tilt robotic head: visual_analysis Class Reference
visual_analysis Class Reference
robohead_drivers
The class used to get images form the camera and track objects in these images. This class contains all the necessary methods to get images from the camera and search colors or faces inside them. Most of this methods take as argument the variables where the position from image will be stored.
#include <visual_analysis.h>
Public Member Functions
visual_analysis ()
Constructor of the visual_analysis class It creates and initializes a VideoCapture object (the camera), checks if that object is able to get images and sets the HSV values to orange.
~visual_analysis ()
Destructor of the class.
bool get_img (Mat &original_img)
It fills a matrix with the data obtined form a captured frame.
int get_color (double &x, double &y, Mat &original_img, int min_H_, int max_H_, int min_S_, int max_S_, int min_V_, int max_V_)
It searches for a specific color in the image Given the image and the range of colors to search in HSV system, it gets the coordinates in the image where the color is and save it in x and y variables.
int get_ball (double &x, double &y, Mat &original_img)
It searches for a orange ball It searches for an orange ball and return its position in the image. It can be useful to test various features.
int get_face (double &x, double &y, Mat &original_img)
It searches for a face in an image It will return the position of the biggest face that it's able to find. Depending on the camera, the face recognition can vary, so it's not very reilable. NOTE: It has some trouble with people wearing glasses...
void get_circle (double &x, double &y, Mat &original_img)
It searches for a face in an image.
Detailed Description
Definition at line 23 of file visual_analysis.h.
Member Function Documentation
bool visual_analysis::get_img (Mat & original_img)
Parameters
opiginal_img A matrix that will contain the captured frame
Returns
bool Returns true if success
Definition at line 39 of file visual_analysis.cpp.
Referenced by CRobohead::follow_ball(), CRobohead::follow_color(), and CRobohead::follow_face().
int visual_analysis::get_color (double & x, double & y, Mat & original_img, int min_H_, int max_H_, int min_S_, int max_S_, int min_V_, int max_V_)
Parameters
x The double where the x coordinate form image will be saved
y The double where the y coordinate from image will be saved
opiginal_img A matrix that contain the frame to analize
min_H_ Minimum hue to search
max_H_ Maximum hue to search
min_S_ Minimum saturatuion to search
max_S_ Maximum saturatuion to search
min_V_ Minimun color valur to search
max_V_ Maximum color value to search
Returns
It returns an integrer that can be used to set a face expression later.
Definition at line 47 of file visual_analysis.cpp.
Referenced by CRobohead::follow_color().
int visual_analysis::get_ball (double & x, double & y, Mat & original_img)
Parameters
x The double where the x coordinate form image will be saved
y The double where the y coordinate from image will be saved
opiginal_img A matrix that contain the frame to analize
Returns
It returns an integrer that can be used to set a face expression later.
Definition at line 99 of file visual_analysis.cpp.
Referenced by CRobohead::follow_ball().
int visual_analysis::get_face (double & x, double & y, Mat & original_img)
Parameters
x The double where the x coordinate form image will be saved
y The double where the y coordinate from image will be saved
opiginal_img A matrix that contain the frame to analize
Returns
It returns an integrer that can be used to set a face expression later.
Definition at line 151 of file visual_analysis.cpp.
Referenced by CRobohead::follow_face().
void visual_analysis::get_circle (double & x, double & y, Mat & original_img)
Parameters
x The double where the x coordinate form image will be saved
y The double where the y coordinate from image will be saved
opiginal_img A matrix that contain the frame to analize
Definition at line 220 of file visual_analysis.cpp.
The documentation for this class was generated from the following files:
/home/agarcia/code/robotic_head/trunk/src/visual_analysis.h
/home/agarcia/code/robotic_head/trunk/src/visual_analysis.cpp