This is a library for controlling a pan and tilt robotic head: CRobohead Class Reference
CRobohead Class Reference
Public Member Functions
CRobohead ()
Main constructor of the robohead class It configures other objects such as mechanical, visual_analysis and face ones.
~CRobohead ()
Destructor of the robohead class.
void follow_face ()
The head will follow the biggest face that visual_analysis is able to find.
void follow_ball ()
The head will follow an orange ball, used in testing.
void follow_color (int min_H_, int max_H_, int min_S_, int max_S_, int min_V_, int max_V_)
The head will follow a specific colour It follows a color given range of it in HSV system.
void orient_to (int x, int y, int z)
It moves the head to given coordinates from the space.
void look_at (int x, int y, int z)
It moves the eyes to look at given coordinates from the space.
void expression (int face)
The face shows an expression.
Detailed Description
Definition at line 25 of file robohead.h.
Member Function Documentation
void CRobohead::follow_color (int min_H_, int max_H_, int min_S_, int max_S_, int min_V_, int max_V_)
Parameters
min_H_ Minimum hue to search
max_H_ Maximum hue to search
min_S_ Minimum saturatuion to search
max_S_ Maximum saturatuion to search
min_V_ Minimun color valur to search
max_V_ Maximum color value to search
Definition at line 74 of file robohead.cpp.
References face::follow(), visual_analysis::get_color(), and visual_analysis::get_img().
void CRobohead::orient_to (int x, int y, int z)
Todo:
Write the code for robohead::orient_to
Parameters
x The x coordinate from the space
y The y coordinate from the space
z The z coordinate from the space
void CRobohead::look_at (int x, int y, int z)
Todo:
Write the code for robohead::look_at
Parameters
x The x coordinate from the space
y The y coordinate from the space
z The z coordinate from the space
void CRobohead::expression (int face)
Parameters
face An int that refers to an expression according to the following table. 1.- Happiness 2.- Surprise 3.- Anger 4.- Sadness 5.- Fear
Definition at line 98 of file robohead.cpp.
References face::expression().
The documentation for this class was generated from the following files:
/home/agarcia/code/robotic_head/trunk/src/robohead.h
/home/agarcia/code/robotic_head/trunk/src/robohead.cpp