This is a library for controlling a pan and tilt robotic head: face Class Reference
face Class Reference
robohead_drivers
A class for drawing a face in the screen This class contain various methods that you can use with a digital face. It can show different faces with different expressions and it can move the eyelids to a specific position or follow something with them (useful with the visual_analysis class).
#include <face.h>
Public Member Functions
face (int width, int height)
Main constructor of the face class. It sets some variables from the class, and while loading, it shows a scared face. NOTE: at the moment it works for squares, height and width must be the same value.
face ()
A void constructor, useful for declaring it in classes as private.
~face ()
Destructor of the class.
void follow (int x, int y)
It moves the eyes according to coordinates given from the screen.
void look_at (int x, int y, int z)
It moves the eyes on time according to given coordinates from the space.
void expression (int face)
The face shows an expression.
Detailed Description
Definition at line 18 of file face.h.
Constructor & Destructor Documentation
face::face (int width, int height)
Parameters
width The width of the face to be shown
height The height of the face to be shown
Definition at line 10 of file face.cpp.
References expression().
Member Function Documentation
void face::follow (int x, int y)
Parameters
x The x coordinate
y The y coordinate
Definition at line 42 of file face.cpp.
References expression().
Referenced by CRobohead::follow_ball(), CRobohead::follow_color(), and CRobohead::follow_face().
void face::look_at (int x, int y, int z)
Todo:
Write the code for the face::look_at method
Parameters
x The x coordinate from the space
y The y coordinate from the space
z The z coordinate from the space
void face::expression (int face)
Parameters
face An int that refers to an expression according to the following table: 1.- Happiness 2.- Surprise 3.- Anger 4.- Sadness 5.- Fear
Definition at line 81 of file face.cpp.
Referenced by CRobohead::expression(), face(), and follow().
The documentation for this class was generated from the following files:
/home/agarcia/code/robotic_head/trunk/src/face.h
/home/agarcia/code/robotic_head/trunk/src/face.cpp